# Arm Trajectory Controllers ---------------------------------------
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

# stand Trajectory Controllers ---------------------------------------
  stand_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - slider_link_rail_stand_right_joint
      - robot_stand_slider_joint